const CartActionTypes = {
  FETCH_DATA_START: "FETCH_DATA_START",
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  FETCH_DATA_FALIURE: "FETCH_DATA_FALIURE",
  ADD_CART_ITEM_START: "ADD_CART_ITEM_START",
  ADD_CART_ITEM_SUCCESS: "ADD_CART_ITEM_SUCCESS",
  ADD_CART_ITEM_FAILURE: "ADD_CART_ITEM_FAILURE",
  REMOVE_CART_ITEM_START: "REMOVE_CART_ITEM_START",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
  CLEAR_CART_ITEM_START: "CLEAR_CART_ITEM_START",
  CLEAR_CART_ITEM_SUCCESS: "CLEAR_CART_ITEM_SUCCESS",
  CLEAR_CART_ITEM_FAILURE: "CLEAR_CART_ITEM_FAILURE",
};

export default CartActionTypes;
