export const ItemsActionTypes = {
  FETCH_ITEMS_START: "FETCH_ITEMS_START",
  FETCH_ITEMS_SUCCESS: "FETCH_ITEMS_SUCCESS",
  FETCH_ITEMS_FALIURE: "FETCH_ITEMS_FALIURE",
  FETCH_IMAGES_START: "FETCH_IMAGES_START",
  FETCH_IMAGES_SUCCESS: "FETCH_IMAGES_SUCCESS",
  FETCH_IMAGES_FALIURE: "FETCH_IMAGES_FALIURE",
};
